// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_OtKap0R5za_4cCVNP8eBCWDnfkW3m44',
    appId: '1:446621147524:web:3745abd5c2756559733dd1',
    messagingSenderId: '446621147524',
    projectId: 'smart-travel-app-a2bfa',
    authDomain: 'smart-travel-app-a2bfa.firebaseapp.com',
    storageBucket: 'smart-travel-app-a2bfa.firebasestorage.app',
    measurementId: 'G-ZJ3C684HJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OtKap0R5za_4cCVNP8eBCWDnfkW3m44',
    appId: '1:1082012345678:android:abc123def456',
    messagingSenderId: '1082012345678',
    projectId: 'smart-travel-app',
    storageBucket: 'smart-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_OtKap0R5za_4cCVNP8eBCWDnfkW3m44',
    appId: '1:1082012345678:ios:abc123def456',
    messagingSenderId: '1082012345678',
    projectId: 'smart-travel-app',
    storageBucket: 'smart-travel-app.appspot.com',
    iosBundleId: 'com.example.smartTravelApp',
  );
}

